---
title: "Tutorial"
author: "Vardhan Mehan, Raymond Bao, Chanseok Lee"
date: "5/11/2019"
output: md_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(broom)
library(tidyr)
```

Here, we read the csv file we want to use and make a dataframe for it.

```{r read_csv, include=TRUE}
df <- read.csv("master.csv")

df <- df %>%
  mutate(gdp_per_capita = gdp_per_capita....)

countries <- df %>%
  group_by(country) %>%
  summarize(suicides = sum(as.numeric(suicides_no)), population = sum(as.numeric(population)), suicides_per_100k = 100000 * (suicides/population)) %>%
  arrange(desc(suicides_per_100k))

gdp <- df %>%
  group_by(gdp_per_capita) %>%
  summarize(suicides = sum(as.numeric(suicides_no)), population = sum(as.numeric(population)), suicides_per_100k = 100000 * (suicides/population))

time_df <- df %>%
  group_by(year) %>%
  summarize(population = sum(as.numeric(population)), suicides = sum(as.numeric(suicides_no)), suicides_per_100k = 100000* (suicides/population))

sex <- df %>%
  group_by(sex) %>%
  summarize(population = sum(as.numeric(population)), suicides = sum(as.numeric(suicides_no)), suicides_per_100k = 100000*(suicides/population))
df

age_group <- df %>%
  group_by(age) %>%
  summarize(population = sum(as.numeric(population)), suicides = sum(as.numeric(suicides_no)), suicides_per_100k = 100000*(suicides/population))
countries 
  
gdp
time_df
sex
age_group

```


```{r hehe, fig.width = 10, fig.height=15, include = TRUE}
countries_plot <- countries %>%
  ggplot(aes(x = factor(country, ordered=TRUE, levels=rev(countries$country)), y = suicides_per_100k, fill=suicides_per_100k)) +
  geom_bar(stat="identity") + 
  coord_flip() +
  scale_y_continuous(breaks=seq(0,45,5)) +
  labs(title = "Country vs Suicides per 100k", x = "Country", y = "Suicides per 100k")

gdp_plot <- gdp %>%
  ggplot(aes(x = gdp_per_capita, y = suicides_per_100k)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks=seq(0,200000,10000)) +
  labs(title = "GDP per Capita vs Suicides per 100k", x = "GDP per Capita", y = "Suicides per 100k")
time_plot <- time_df %>%
  ggplot(aes(x = year, y = suicides_per_100k)) +
  geom_point() +
  geom_line() +
  labs(title = "Suicides per 100k over time", x = "Time", y = "Suicides per 100k")

sex_plot <- sex %>%
  ggplot(aes(x = sex, y = suicides_per_100k, fill=sex)) +
  geom_bar(stat="identity") +
  labs(title = "Gender vs Suicides per 100k", x = "Gender", y = "Suicides per 100k")

age_group_plot <- age_group %>%
  ggplot(aes(x = factor(age, ordered=TRUE, levels=c("5-14 years","15-24 years","25-34 years","35-54 years","55-74 years","75+ years")), y= suicides_per_100k, fill=age)) +
  geom_bar(stat="identity") +
  labs(title = "Age Group vs Suicides per 100k", x = "Age group", y = "Suicides per 100k")


countries_plot
gdp_plot
time_plot
sex_plot
age_group_plot
```

```{r gender_and_country, fig.width=10, fig.height=15, include=TRUE}
sex_country <- df %>%
  group_by(country, sex) %>%
  summarize(population = sum(as.numeric(population)), suicides = sum(as.numeric(suicides_no)), suicides_per_100k = 100000 * (suicides/population)) %>%
  arrange(desc(suicides))

sex_country
sex_country %>%
  ggplot(aes(x = factor(country, ordered=TRUE, levels=rev(countries$country)), y = suicides_per_100k, fill = sex)) +
  geom_bar(stat = "Identity") +
  coord_flip()

age_country <- df %>%
  group_by(country, age) %>%
  summarize(population = sum(as.numeric(population)), suicides = sum(as.numeric(suicides_no)), suicides_per_100k = 100000 * (suicides/population)) %>%
  arrange(desc(suicides))

age_country %>%
  ggplot(aes(x = factor(country, ordered=TRUE, levels=rev(countries$country)), y = suicides_per_100k, fill = age)) +
  geom_bar(stat="Identity") +
  coord_flip()
```





